version: "3.1"
services:
  mqtt:
    image: pascaldevink/rpi-mosquitto
    ports:
     - "1883:1883"
  mongo-init:
    image: nonoroazoro/rpi-mongo
    links:
      - mongo
    command: mongo hulkdevfestgame --host mongo --eval "db.createCollection('results',{capped:true,size:10000})"
  mongo:
    image: nonoroazoro/rpi-mongo
    volumes:
      - /var/mongo/data/db:/data/db
      - /var/mongo/data/configdb:/data/configdb
  tweetmodule:
    image: hulkdevfest2017/tweetmodule:1.0
    links:
      - mqtt
    environment:
      - twitter_consumer_key
      - twitter_consumer_secret
      - twitter_access_token
      - twitter_access_token_secret
  soundmodule:
    image: hulkdevfest2017/soundmodule:1.0
    volumes:
      - /opt/vc/lib:/opt/vc/lib
    devices:
      - /dev/snd
    links:
      - mqtt
  persistencemodule:
    image: hulkdevfest2017/persistencemodule:1.0
    depends_on:
      - mongo-init
    links:
      - mongo
      - mqtt
  resultsmodule:
    image: hulkdevfest2017/resultsmodule:1.0
    ports:
      - "80:3100"
    depends_on:
      - mongo-init
    links:
      - mongo
  arduinogateway:
    image: hulkdevfest2017/arduino-gateway:1.0
    links:
      - mqtt
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
      - "/dev/ttyUSB2:/dev/ttyUSB3"
      - "/dev/ttyUSB4:/dev/ttyUSB4"
